/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import static Vistas.Login.datosPersonal;
import bbdd.Conexion;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Destro
 */
public class MenuPrincipal extends javax.swing.JFrame {

   DefaultTableModel mod;
    public MenuPrincipal() throws SQLException {
        
        initComponents();
        
       mod = (DefaultTableModel) tabla.getModel();
       
        
        Date fecha = new Date();
        campofecha.setText(fecha.toString());
        if("MEDICO".equals(datosPersonal[2])){
        camponombre.setText("Facultativo " + datosPersonal[0]);
        camponumerocolegiado.setText("Numero del colegiado " + datosPersonal[1]);
        campoagenda.setText("AGENDA DE CITAS MEDICAS");
        botonconsultas.setEnabled(true);
        botonpacientes.setEnabled(true);
         Conexion.conectar();
       Conexion.cargarcitasMedicas(mod);
       Conexion.cerrarConexion();
        }else if ("ENFERMERIA".equals(datosPersonal[2])){
        camponombre.setText("Facultativo " + datosPersonal[0]);
        camponumerocolegiado.setText("Numero del colegiado " + datosPersonal[1]);
        campoagenda.setText("AGENDA DE CITAS DE ENFERMERIA");
        botonenfermeria.setEnabled(true);
        Conexion.conectar();
        Conexion.cargarcitasEnfermeria(mod);
         Conexion.cerrarConexion();
        }else if ("ADMIN".equals(datosPersonal[2])){
        camponombre.setText("Administrados " + datosPersonal[0]);
        
        botonpersonal.setEnabled(true);
        Conexion.cerrarConexion();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campofecha = new javax.swing.JLabel();
        camponombre = new javax.swing.JLabel();
        camponumerocolegiado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonconsultas = new javax.swing.JButton();
        botonenfermeria = new javax.swing.JButton();
        botonpacientes = new javax.swing.JButton();
        botonpersonal = new javax.swing.JButton();
        campoagenda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1275, 750));
        setMinimumSize(new java.awt.Dimension(1275, 750));
        setPreferredSize(new java.awt.Dimension(1275, 750));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        campofecha.setText("jLabel1");

        camponombre.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_good.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(camponumerocolegiado, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(camponombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(campofecha, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 751, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campofecha)
                        .addGap(18, 18, 18)
                        .addComponent(camponombre)
                        .addGap(18, 18, 18)
                        .addComponent(camponumerocolegiado)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        botonconsultas.setBackground(new java.awt.Color(0, 204, 204));
        botonconsultas.setForeground(new java.awt.Color(255, 255, 255));
        botonconsultas.setText("Consultas");
        botonconsultas.setEnabled(false);
        botonconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonconsultasActionPerformed(evt);
            }
        });

        botonenfermeria.setBackground(new java.awt.Color(0, 204, 204));
        botonenfermeria.setForeground(new java.awt.Color(255, 255, 255));
        botonenfermeria.setText("Enfermeria");
        botonenfermeria.setEnabled(false);
        botonenfermeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonenfermeriaActionPerformed(evt);
            }
        });

        botonpacientes.setBackground(new java.awt.Color(0, 204, 204));
        botonpacientes.setForeground(new java.awt.Color(255, 255, 255));
        botonpacientes.setText("Pacientes");
        botonpacientes.setEnabled(false);
        botonpacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpacientesActionPerformed(evt);
            }
        });

        botonpersonal.setBackground(new java.awt.Color(0, 204, 204));
        botonpersonal.setForeground(new java.awt.Color(255, 255, 255));
        botonpersonal.setText("Personal Medico");
        botonpersonal.setEnabled(false);
        botonpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpersonalActionPerformed(evt);
            }
        });

        campoagenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoagenda.setForeground(new java.awt.Color(255, 255, 255));
        campoagenda.setText("AGENDAS DE CITAS MEDICAS");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "DIA", "HORA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/principal.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoagenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonconsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addComponent(botonpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(botonenfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(botonpersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonconsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonenfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonpersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoagenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonconsultasActionPerformed
       Medico m = new Medico();
       m.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonconsultasActionPerformed

    private void botonenfermeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonenfermeriaActionPerformed
   Enfermeria e = new Enfermeria();
   e.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonenfermeriaActionPerformed

    private void botonpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpersonalActionPerformed
       PersonalMedico pm = new PersonalMedico(this, rootPaneCheckingEnabled);
       pm.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonpersonalActionPerformed

    private void botonpacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpacientesActionPerformed
        Pacientes p = new Pacientes(this, rootPaneCheckingEnabled);
        p.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonpacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonconsultas;
    private javax.swing.JButton botonenfermeria;
    private javax.swing.JButton botonpacientes;
    private javax.swing.JButton botonpersonal;
    private javax.swing.JLabel campoagenda;
    private javax.swing.JLabel campofecha;
    private javax.swing.JLabel camponombre;
    private javax.swing.JLabel camponumerocolegiado;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
